#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# Requirements:

#	Accepts 4 parameters
#	The path to the file to be transferred
# 	The IP of the server we want to transfer the file to
#	The username scp connects with
#	The path to the SSH private key that scp uses

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4
if [[ $# -lt 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
fi
