#!/usr/bin/env bash
# configuring http header to servers
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
line="\\\trewrite ^/redirect_me https:\/\/github.com\/maureen-chepr permanent;"
sudo sed -i "26i $line" /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx restart
