#!/usr/bin/env bash
# script that displays Best School 10 times,but the 9th iteration, displays Best School and Hi on a new line.

i=1
while [ "$i" -le 10 ]; do
    if [ "$i" -eq 9 ]; then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi

    ((i++))
done

exit 0
